### PR TITLE
Support OTP 26.2 and elixir 1.16.0 for CI

### PR DESCRIPTION
**Pull request by GeoffreyPS**
### What does this do on a high level?
This adds checks to this library's CI for the following versions:
- OTP 26.2 and Elixir 1.15.7
- OTP 26.2 and Elixir 1.16.0
- Bump Elixir 1.14 version from `1.14.2` to `1.14.5`

### How was this change made?
I added new entries to the `matrix` field in `main.yml` for the github configuration.

### Why is this change necessary?
This library should keep up with new versions of elixir so as to remain relevant.

### How will this be verified?
- [ ] The PR includes new tests
- [X] Current test suite covers functionality
- [ ] This has been tested locally
- [ ] This has been tested in `dev`

### Any additional information or special handling required on this PR? 

_motivational imagery_
a chimpanzee irons clothes

### CODE REVIEW

**Comment by GeoffreyPS** [comment]
Not sure why the test runners aren't picking this up; will mark as ready for review to see if the runners stop waiting then.

**Comment by GeoffreyPS** [comment]
That doesn't seem to affect the runners. Re-converting to draft.

**Comment by idlehands** [comment]
@GeoffreyPS I tried cancelling and re-running the jobs to no avail. I will try to look into the test runners early next week.

**Comment by GeoffreyPS** [comment]
@idlehands wrote:
> @GeoffreyPS I tried cancelling and re-running the jobs to no avail. I will try to look into the test runners early next week.

No rush! I ran a little bit of this locally with [`act`](https://github.com/nektos/act) and saw some issues while waiting, but I need to circle back to figure out if they're local problems or stuff we'll encounter with the CI runs.

**Comment by idlehands** [comment]
@GeoffreyPS when you can, if you can update from main, you'll get the new Ubuntu version and the test runners will work. Thanks!

**Comment by idlehands** [comment]
Closing this PR a new versions of Elixir and OTP require more in depths changes as covered in https://github.com/Shimmur/checker_cab/pull/38

**Pull request closed without merging**
